language: ruby
cache: bundler
sudo: false
env:
  - FOG_MOCK=true
  - FOG_MOCK=false
matrix:
  fast_finish: true
  include:
    - rvm: 2.1
    - rvm: 2.4.0
    - rvm: 2.4.1
    - rvm: jruby-head
  allow_failures:
    - rvm: jruby-head
notifications:
  email: false
